services:
  test2:
    image: 'alpine:latest'
    volumes:
      - './test:/mnt/test2'
  test3:
    extends:
      file: 'docker-compose.d/templates.yml'
      service: template
  test4:
    extends:
      file: 'docker-compose.d/templates.yml'
      service: template
    volumes:
      - './test:/mnt/test4'
